---
driver_plugin: ec2
driver_config:
  aws_access_key_id: <%= ENV['AWS_AWS_ACCESS_KEY_ID'] %>
  aws_secret_access_key: <%= ENV['AWS_AWS_SECRET_ACCESS_KEY'] %>
  aws_ssh_key_id: <%= ENV['AWS_AWS_SSH_KEY_ID'] %>
  ssh_key: <%= File.expand_path('~/.ssh/id_rsa-aws') %>
  region: us-east-1
  availability_zone: us-east-1b
  flavor_id: m3.xlarge
  groups:
  - default
  require_chef_omnibus: true

platforms:
- name: ubuntu-12.04
  driver_config:
    image_id: ami-fd20ad94
    username: ubuntu
  run_list:
  - recipe[apt]
- name: ubuntu-10.04
  driver_config:
    image_id: ami-c7b202ae
    username: ubuntu
  run_list:
  - recipe[apt]
- name: centos-6.3
  driver_config:
    image_id: ami-ef5ff086
    username: ec2-user
  run_list:
  - recipe[yum::epel]
